app/controllers/mentors/sessions_controller.rb
app/views/mentors/sessions/edit.html.erb
app/views/mentors/sessions/show.html.erb
app/views/pages/home.html.erb
config/routes.rb

Views for mentors 2

---

app/controllers/prospectives/registrations_controller.rb
app/views/prospectives/registrations/new.html.erb
config/routes.rb

completed controller routes views for new create prospectives

completed controller routes views for new create prospectives

---

app/assets/stylesheets/pages/_card.scss
app/assets/stylesheets/pages/_index.scss
app/views/mentors/sessions/index.html.erb

cards for index complete

---

Gemfile
Gemfile.lock
app/controllers/mentors/sessions_controller.rb
app/models/mentor.rb
app/views/mentors/sessions/index.html.erb
db/seeds.rb

Added basic ElasticSearch functionality. Can edit the search settings later if necessary: https://github.com/ankane/searchkick
You might need to follow the setup instructions for installing ElasticSearch on your machine: 
brew install elasticsearch
brew services start elasticsearch
https://kitt.lewagon.com/knowledge/lectures/05-Rails%2F09-Airbnb-SMTP#source

Elastic search

---

app/views/mentors/sessions/index.html.erb

show default avatar if photo doesnt exist

show default avatar if photo doesnt exist

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/mentors/sessions/show.html.erb

mentors show page

---

Gemfile.lock

gemlock fix

---

app/assets/stylesheets/components/_prosp-sign-up.scss
app/assets/stylesheets/pages/_show.scss
app/views/mentors/sessions/show.html.erb

updated profile page

---

config/environments/production.rb

environment production

---

app/controllers/mentors/sessions_controller.rb
app/javascript/components/navbar.js

deleted duplicate function

---

app/assets/stylesheets/components/_navbar_two.scss
config/environments/development.rb

Fix navbar error2

---

app/models/booking.rb

deleted numerical in booking model

deleted numerical in booking model

---

Gemfile

moved faker

---

app/views/mentors/sessions/edit.html.erb
app/views/mentors/sessions/index.html.erb
app/views/mentors/sessions/show.html.erb

images for mentors updated

---

app/assets/stylesheets/pages/_show.scss
app/views/mentors/sessions/show.html.erb

style for messaging box

---

app/javascript/components/chat.js
app/views/mentors/sessions/show.html.erb

1. Previous messages now load!
2. Unique channels can be generated for each prospective and mentor combination!

Improve chat 3

---

Gemfile
Gemfile.lock
app/controllers/mentors/sessions_controller.rb
app/models/mentor.rb

Fixed search to pg

---

app/assets/stylesheets/pages/_show.scss
app/views/mentors/sessions/index.html.erb
app/views/mentors/sessions/show.html.erb
app/views/pages/home.html.erb

footers done

---

app/assets/stylesheets/pages/_show.scss
app/views/mentors/sessions/show.html.erb

go back button added

---

app/views/mentors/sessions/show.html.erb
db/seeds.rb

Fixed overwritten code for ID generation

---

app/views/mentors/sessions/index.html.erb
app/views/shared/_navbar_two.html.erb

link avatar to mentors and prospectves sign in

link avatar to mentors and prospectves sign in

---

app/controllers/mentors/sessions_controller.rb
app/views/shared/_navbar.html.erb

fixed login error and sorted mentors alphabetically

fixed login error and sorted mentors alphabetically

---

app/models/mentor.rb

added nationality to search

---

app/views/mentors/sessions/show.html.erb

remove edit profile

---

app/controllers/mentors/sessions_controller.rb
app/views/mentors/sessions/index.html.erb

sorting reviews working

---

app/controllers/mentors/sessions_controller.rb
app/views/mentors/sessions/index.html.erb

add more sortings

---

app/views/mentors/sessions/show.html.erb

university stats charts added

---

app/javascript/components/chat.js

channel changed to 3 on chat.js

---

app/assets/stylesheets/components/_card.scss
app/views/pages/home.html.erb

changes to my approach

---

app/views/mentors/sessions/show.html.erb

changes to charts on show page

---

app/views/mentors/sessions/show.html.erb

Move show stars

---

db/seeds.rb

added architecture
